name: Build and Release Electron App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.0'
      timeout-minutes: 10
      
    - name: Install dependencies (Windows)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        npm config set legacy-peer-deps true
        npm install --no-audit --no-fund
        npm install -g rimraf
      timeout-minutes: 15
      
    - name: Install dependencies (macOS/Linux)
      if: matrix.os != 'windows-latest'
      run: |
        npm config set legacy-peer-deps true
        npm install --no-audit --no-fund
        npm install -g rimraf
      timeout-minutes: 15
      
    # Skip linting for now since there's no ESLint config
    # - name: Run linter
    #   run: npm run lint
      
    - name: Build app (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        npx rimraf dist dist-electron release
        npx tsc
        npx vite build
        npx electron-builder --win --config.win.signAndEditExecutable=false
      timeout-minutes: 30
      
    - name: Build app (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        npx rimraf dist dist-electron release
        npx tsc
        npx vite build
        npx electron-builder
      timeout-minutes: 30
      
    - name: Build app (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        npx rimraf dist dist-electron release
        npx tsc
        npx vite build
        npx electron-builder
      timeout-minutes: 30
      
    - name: Upload artifacts (Windows)
      if: matrix.os == 'windows-latest' && success()
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: release/*.exe
        
    - name: Upload artifacts (macOS)
      if: matrix.os == 'macos-latest' && success()
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: release/*.dmg
        
    - name: Upload artifacts (Linux)
      if: matrix.os == 'ubuntu-latest' && success()
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: release/*.AppImage
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && success()
      with:
        files: |
          release/*.exe
          release/*.dmg
          release/*.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
